urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home_view, name='home'),
    path('students/', views.students, name='students'),
    path('staffs/', views.staffs, name='staffs'),
    path('courses/', views.courses, name='courses'),
    path('data/', views.course_view, name='data'),
    path('<int:course_id>/', views.course_data_view, name='course-data'),
    path('students/<int:student_id>/', views.student_data_view, name='student-data'),
    path('staffs/<int:staff_id>/', views.staff_data_view, name='staff-data'),
    path('new-student/', views.Student_create_view.as_view(), name='create-student'),
    path('students/delete/<int:student_id>/', views.Student_delete_view.as_view(), name='delete-student'),
    path('students/update/<int:student_id>/', views.Student_update_view.as_view(), name='update-student'),
    path('new-staff/', views.Staff_create_view.as_view(), name='create-staff'),
    path('staffs/delete/<int:staff_id>/', views.Staff_delete_view.as_view(), name='delete-staff'),
    path('staffs/update/<int:staff_id>/', views.Staff_update_view.as_view(), name='update-staff'),
]

models.py
from django.db import models
from django.utils import timezone


class Courses(models.Model):
    course = models.CharField(max_length=101)
    num = models.IntegerField(default=0)

    def __str__(self):
        return self.course


class Students(models.Model):
    name = models.CharField(max_length=60, blank=False)
    course = models.ForeignKey(Courses, on_delete=models.CASCADE)
    age = models.IntegerField(default=0, blank=True)
    level = models.IntegerField(default=1)
    email = models.EmailField(blank=False)
    phone_number = models.IntegerField()
    matric_number = models.CharField(max_length=20)
    date_admitted = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.name


class Staff(models.Model):
    name = models.CharField(max_length=60, blank=False)
    lecture_course = models.ForeignKey(Courses, on_delete=models.CASCADE, blank=True)
    course_length = models.IntegerField(default=0)
    job_type = models.CharField(max_length=101)
    email = models.EmailField(blank=False)
    phone_number = models.IntegerField()
    date_employed = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.name

views.py
from django.shortcuts import render
from .models import Students, Staff, Courses
from django.views.generic import UpdateView, DeleteView, CreateView


def home_view(request):
    return render(request, 'manager_app/home.html', {'title': 'Home Page...'})


def students(request):
    s = Students.objects.all()
    context = {
        'students': s.order_by,
    }
    return render(request, 'manager_app/students.html', context)


def staffs(request):
    st = Staff.objects.all()
    context = {
        'staffs': st
    }
    return render(request, 'manager_app/staffs.html', context)


def courses(request):
    c = Courses.objects.all()
    st = Students.objects.all()

    context = {
        'courses': c,
        'students': st,
    }

    return render(request, 'manager_app/courses.html', context)


def course_view(request):
    course = Courses.objects.all()
    st = Students.objects.all()

    context = {
        'courses': course,
        'students': st,
    }
    return render(request, 'manager_app/stu-course.html', context)


def course_data_view(request, course_id):
    q = Courses.objects.get(id=course_id)
    context = {
        'course': q,
    }
    return render(request, 'manager_app/course_view.html', context)


def student_data_view(request, student_id):
    q = Students.objects.get(id=student_id)
    context = {
        'student': q,
    }
    return render(request, 'manager_app/student_view.html', context)


def staff_data_view(request, staff_id):
    q = Staff.objects.get(id=staff_id)
    context = {
        'staff': q,
    }
    return render(request, 'manager_app/staff_view.html', context)


class Student_create_view(CreateView):
    model = Students
    fields = ["name", 'course', 'email', 'phone_number', 'matric_number', 'date_admitted']
    template_name = 'manager_app/add_student.html'
    success_url = '/students'


class Student_delete_view(DeleteView):
    model = Students
    template_name = 'manager_app/delete_student.html'
    success_url = '/students'
    pk_url_kwarg = 'student_id'


class Student_update_view(UpdateView):
    model = Students
    fields = ["name", 'course', 'email', 'phone_number', 'matric_number', 'date_admitted']
    template_name = 'manager_app/add_student.html'
    pk_url_kwarg = 'student_id'
    success_url = '/students'


class Staff_create_view(CreateView):
    model = Staff
    fields = ["name", 'lecture_course', 'job_type', 'email', 'phone_number', 'date_employed']
    template_name = 'manager_app/add_staff.html'
    success_url = '/staffs'


class Staff_delete_view(DeleteView):
    model = Staff
    template_name = 'manager_app/delete_staff.html'
    success_url = '/staffs'
    pk_url_kwarg = 'staff_id'


class Staff_update_view(UpdateView):
    model = Staff
    fields = ["name", 'lecture_course', 'job_type', 'email', 'phone_number', 'date_employed']
    template_name = 'manager_app/add_staff.html'
    pk_url_kwarg = 'staff_id'
    success_url = '/staffs'

templates/manager_app/add_staff.html
{% extends 'manager_app/base.html' %}
{% block content %}
<form method="post">
    {% csrf_token %}
    <fieldset>
        <legend>Add a new staff</legend>
        {{ form }}
    </fieldset>
    <button type="submit">Add Staff</button>
</form>
{% endblock content %}

templates/manager_app/add_student.html
{% extends 'manager_app/base.html' %}
{% block content %}
<form method="post">
    {% csrf_token %}
    <fieldset>
        <legend>Add a new student</legend>
        {{ form }}
    </fieldset>
    <button type="submit">Add Student</button>
</form>
{% endblock content %}

templates/manager_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% if title %}
        <title>{{ title }}</title>
    {% else %}
        <title>School management system</title>
    {% endif %}
</head>
<body>
    <nav>
        <ul>
            <a href="{% url 'home' %}"><li>Home</li></a>
            <a href="#"><li>Events</li></a>
            <a href="{% url 'students' %}"><li>Students</li></a>
            <a href="{% url 'staffs' %}"><li>Staffs</li></a>
            <a href="#"><li>About</li></a>
            <a href="{% url 'courses' %}"><li>Courses</li></a>
        </ul>
    </nav>

{% block content %}
{% endblock %}
</body>
</html>

templates/manager_app/course_view.html
{% extends 'manager_app/base.html' %}

{% block content %}
    <span>
        <table border="3" bordercolor = "pink">
            <caption>{{ course }}'s data view</caption>
            <tr>
                <th>Course</th>
                <th><a href="#">No. of students offering</a></th>
                <th>Students</th>
            </tr>

            <tr>
                <td>{{ course }}</td>
                <td>{{ course.students_set.count }}</td>
            </tr>
        </table>
        <table border="2" bordercolor=" cyan">
            <caption>{{ course }}'s students</caption>
            <tr>
                <td>Students</td>
            </tr>
            <tr>
                {% for student in course.students_set.all %}
                    <td>{{ student }}</td>
                {% endfor %}
            </tr>
        </table>
    </span>
{% endblock content %}

templates/manager_app/courses.html
{% extends 'manager_app/base.html' %}
{% block content %}

<table border="5" bordercolor="black" width="200">
    <caption>Course Table</caption>
    <tr>
        <th>Course</th>
        <th>No. of students offering</th>
    </tr>
        {% for course in courses %}
            <tr>
                <td><a href="{% url 'course-data' course.id %}">{{ course }}</a></td>
                <td>{{ course.students_set.count }}</td>
            </tr>
        {% endfor %}
</table>

{% endblock content %}

templates/manager_app/delete_staff.html
{% extends 'manager_app/base.html' %}
{% block content %}
    <p>Are you sure you want to delete {{ object.name }}'s data?</p>
    <form method="post">
        {% csrf_token %}
        <span><button type="submit">Yes Remove</button> <a href="{% url 'staffs' %}">Go back</a></span>
    </form>
{% endblock content %}

templates/manager_app/delete_student.html
{% extends 'manager_app/base.html' %}
{% block content %}
    <p>Are you sure you want to delete {{ object.name }}'s data?</p>
    <form method="post">
        {% csrf_token %}
        <span><button type="submit">Yes Remove</button> <a href="{% url 'students' %}">Go back</a></span>
    </form>
{% endblock content %}

templates/manager_app/home.html
{% extends 'manager_app/base.html' %}

{% block content %}
    <p>Welcome to our home page</p>
{% endblock content %}

templates/manager_app/staff_view.html
{% extends 'manager_app/base.html' %}
{% block content %}
    <a href="{% url 'update-staff' staff.id %}">Update {{ staff.name }}'s details</a> <br>
    <a href="{% url 'delete-staff' staff.id %}">Delete {{ staff.name }}'s details from database?</a>
    <table border="3" bordercolor = "cyan" width="800">
        <caption>{{ staff }}'s data</caption>
        <tr>
            <th>Name</th>
            <th>lecturing course</th>
            <th>number of courses taken</th>
            <th>Email</th>
            <th>Phone Number</th>
            <th>Job Type</th>
            <th>Date Employed</th>
        </tr>

        <tr>
            <td>{{ staff.name }}</td>
            <td>{{ staff.lecture_course }}</td>
            <td>{{ staff.course_length }}</td>
            <td>{{ staff.email }}</td>
            <td>{{ staff.phone_number }}</td>
            <td>{{ staff.job_type }}</td>
            <td>{{ staff.date_employed|date:"F d Y" }}</td>
        </tr>
    </table>
{% endblock content %}

templates/manager_app/staffs.html
{% extends 'manager_app/base.html' %}

{% block content %}
    <a href="{% url 'create-staff' %}">Add New Staff</a>
    <table border="6" bordercolor = 'black' width="800" height = "150">
        <caption>Staff's Data</caption>
            <tr>
                <th>Name</th>
                <th>lecturing course</th>
                <th>number of courses taken</th>
                <th>Email</th>
                <th>Phone Number</th>
                <th>Job Type</th>
                <th>Date Employed</th>
            </tr>
        {% for staff in staffs %}
            <tr>
                <td><a href="{% url 'staff-data' staff.id %}">{{ staff.name }}</a></td>
                <td>{{ staff.lecture_course }}</td>
                <td>{{ staff.course_length }}</td>
                <td>{{ staff.email }}</td>
                <td>{{ staff.phone_number }}</td>
                <td>{{ staff.job_type }}</td>
                <td>{{ staff.date_employed|date:"F d Y" }}</td>
            </tr>
        {% endfor %}
    </table>
{% endblock content %}

templates/manager_app/stu-course.html
{% extends 'manager_app/base.html' %}
{% block content %}

    {% for course in courses %}
        <table border="2" bordercolor="black" width="700">
            <caption><a href="#">{{ course }}'s data</a> </caption>
            <tr>
                <th>Name</th>
                <th>Level</th>
                <th>Email</th>
                <th>Phone number</th>
                <th>Matric Number</th>
                <th>Date Admitted</th>
            </tr>
            {% for student_set in course.students_set.all %}
                {% for student in students %}
                    {% if student_set == student %}
                        <tr>
                            <td>{{ student.name }}</td>
                            {% if student.level <= 4 %}
                                <td>{{ student.level }}</td>
                            {% else %}
                                <td>Graduated</td>
                            {% endif %}
                            <td>{{ student.email }}</td>
                            <td>{{ student.phone_number }}</td>
                            <td>{{ student.matric_number }}</td>
                            <td>{{ student.date_admitted|date:'Y m d' }}</td>
                        </tr>
                    {% endif %}
                {% endfor %}
            {% endfor %}
        </table>
    {% endfor %}

{% endblock content %}

templates/manager_app/student_view.html
{% extends 'manager_app/base.html' %}

{% block content %}
    <a href="{% url 'update-student' student.id %}">Update {{ student.name }}'s details</a> <br>
    <a href="{% url 'delete-student' student.id %}">Delete {{ student.name }}'s details from database?</a>
    <table border="3" bordercolor = "cyan" width="800">
        <tr>
            <th>Name</th>
            <th>Course</th>
            <th>Level</th>
            <th>Email</th>
            <th>Phone Number</th>
            <th>Matric Number</th>
            <th>Date Admitted</th>
        </tr>
        <tr>
            <td><a href="{% url 'student-data' student.id %}">{{ student.name }}</a></td>
            <td>{{ student.course }}</td>
            {% if student.level <= 4 %}
                <td>{{ student.level }}</td>
            {% else %}
                <td>Graduated</td>
            {% endif %}
            <td>{{ student.email }}</td>
            <td>{{ student.phone_number }}</td>
            <td>{{ student.matric_number }}</td>z
            <td>{{ student.date_admitted| date:"d M Y" }}</td>
        </tr>
    </table>
{% endblock content %}

templates/manager_app/students.html
{% extends 'manager_app/base.html' %}

{% block content %}
    <a href="{% url 'create-student' %}">Add New Student</a>
    <table border="6" bordercolor = 'black' width="300">
        <caption>Students Data</caption>
            <tr>
                <th>Name</th>
                <th>Course</th>
                <th>Level</th>
                <th>Email</th>
                <th>Phone Number</th>
                <th>Matric Number</th>
                <th>Date Admitted</th>
            </tr>
        {% for student in students %}
            <tr>
                <td><a href="{% url 'student-data' student.id %}">{{ student.name }}</a></td>
                <td>{{ student.course }}</td>
                {% if student.level <= 4 %}
                    <td>{{ student.level }}</td>
                {% else %}
                    <td>Graduated</td>
                {% endif %}
                <td>{{ student.email }}</td>
                <td>{{ student.phone_number }}</td>
                <td>{{ student.matric_number }}</td>z
                <td>{{ student.date_admitted| date:"d M Y" }}</td>
            </tr>
        {% endfor %}
    </table>
{% endblock content %}